version: '3'
services:
    esb:
        build: ./src
        ports:
            - "5003:5003"
        volumes:
            - .:/usr/src/
        restart: on-failure 
        depends_on:
            - restaurante
            - repartidor
            - cliente
    restaurante: 
        build: ./src/restaurante
        ports:
            - "5003:5003"
        volumes:
            - .:/usr/src/restaurante
        restart: on-failure 
        depends_on:
            - db
    repartidor: 
        build: ./src/repartidor
        ports:
            - "5003:5003"
        volumes:
            - .:/usr/src/repartidor
        restart: on-failure 
        depends_on:
            - db
    cliente: 
        build: ./src/repartidor
        ports:
            - "3001:3001"
        volumes:
            - .:/usr/src/cliente
        restart: on-failure 
        depends_on:
            - db
    db: 
        image: mongo
        ports:
            - "27017-27019:27017-27019"
        restart: on-failure 


